config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'favorite_categories#index'

  devise_for :users

  resources :favorite_categories do
    resources :favorites

  end

  get 'find_by_order' => 'favorite_categories#find_by_order', as: 'find_by_order'
end

app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id                   :integer          not null, primary key
#  favorite_category_id :integer          not null
#  name                 :string           not null
#  author               :string
#  year                 :integer
#  url                  :string
#  details              :string
#  destription          :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_favorites_on_favorite_category_id  (favorite_category_id)
#

class Favorite < ApplicationRecord
  belongs_to :favorite_category
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite_category
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = @favorite_category.favorites
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = @favorite_category.favorites.build
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = @favorite_category.favorites.build(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorite_category_favorite_path(@favorite_category,@favorite), notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: favorite_category_favorite_path(@favorite_category,@favorite) }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorite_category_favorite_path(@favorite_category,@favorite), notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: favorite_category_favorite_path(@favorite_category,@favorite) }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorite_category_favorites_url(@favorite_category), notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_category
      @favorite_category = current_user.favorite_categories.find(params[:favorite_category_id])
    end

    def set_favorite
      @favorite = @favorite_category.favorites.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:name, :author, :year, :url, :details, :destription)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite, url: [@favorite_category, favorite], local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Categoría: <%= @favorite_category.name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="field">
    <%= form.label :destription %>
    <%= form.text_field :destription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', favorite_category_favorite_path(@favorite_category, @favorite) %> |
<%= link_to 'Back', favorite_category_favorites_path(@favorite_category) %>

app/views/favorites/index.html.erb
<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Year</th>
      <th>Url</th>
      <th>Details</th>
      <th>Destription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.name %></td>
        <td><%= favorite.author %></td>
        <td><%= favorite.year %></td>
        <td><%= favorite.url %></td>
        <td><%= link_to 'Show', favorite_category_favorite_path(@favorite_category,favorite) %></td>
        <td><%= link_to 'Edit', edit_favorite_category_favorite_path(@favorite_category,favorite) %></td>
        <td><%= link_to 'Destroy', favorite_category_favorite_path(@favorite_category,favorite), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_category_favorite_path(@favorite_category) %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorite_category_favorites_path(@favorite_category) %>

app/views/favorites/show.html.erb
<h1><%= @favorite.name %></h1>

<div class="favorites__category">
  Categoría <span class="favorites__category-name"><%= @favorite.favorite_category.name %></span> <%= link_to '(volver a categoría)', favorite_category_favorites_path(@favorite_category) %>
</div>

<div class="favorites__show">

  <div class="favorites__detail">
    <span class="favorites__label">Nombre:</span>
    <span class="favorites__value"><%= @favorite.name %></span>
  </div>

  <div class="favorites__detail">
    <span class="favorites__label">Autor:</span>
    <span class="favorites__value"><%= @favorite.author %></span>
  </div>

  <div class="favorites__detail">
    <span class="favorites__label">Año:</span>
    <span class="favorites__value"><%= @favorite.year %></span>
  </div>

  <div class="favorites__detail">
    <span class="favorites__label">Dirección URL:</span>
    <span class="favorites__value"><%= @favorite.url %></span>
  </div>

  <div class="favorites__detail">
    <span class="favorites__label">Detalles:</span>
    <div class="favorites__detail-value"><%= @favorite.details %></div>
  </div>

  <div class="favorites__detail">
    <span class="favorites__label">Descripción:</span>
    <div class="favorites__detail-value"><%= @favorite.destription %></div>
  </div>

  <%= link_to 'Cambiar', edit_favorite_category_favorite_path(@favorite_category,@favorite), class: 'favorites__edit-btn' %>

</div>