config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'favorite_categories#index'

  devise_for :users

  resources :favorite_categories do
    resources :favorites

  end

  get 'find_by_order' => 'favorite_categories#find_by_order', as: 'find_by_order'
end

app/models/favorite_category.rb
# == Schema Information
#
# Table name: favorite_categories
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  order       :integer          not null
#  name        :string           not null
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_favorite_categories_on_user_id  (user_id)
#

class FavoriteCategory < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :ordered, -> { order(:order) }
end

app/controllers/favorite_categories_controller.rb
class FavoriteCategoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_favorite_category, only: [:show, :edit, :update, :destroy]

  # GET /favorite_categories
  # GET /favorite_categories.json
  def index
    @favorite_categories = current_user.favorite_categories.ordered
  end

  # GET /favorite_categories/1
  # GET /favorite_categories/1.json
  def show
  end

  # GET /favorite_categories/new
  def new
    @favorite_category = current_user.favorite_categories.build
  end

  # GET /favorite_categories/1/edit
  def edit
  end

  # POST /favorite_categories
  # POST /favorite_categories.json
  def create
    @favorite_category = current_user.favorite_categories.build(favorite_category_params)

    respond_to do |format|
      if @favorite_category.save
        format.html { redirect_to @favorite_category, notice: 'Favorite category was successfully created.' }
        format.json { render :show, status: :created, location: @favorite_category }
      else
        format.html { render :new }
        format.json { render json: @favorite_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_categories/1
  # PATCH/PUT /favorite_categories/1.json
  def update
    respond_to do |format|
      if @favorite_category.update(favorite_category_params)
        format.html { redirect_to @favorite_category, notice: 'Favorite category was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_category }
      else
        format.html { render :edit }
        format.json { render json: @favorite_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_categories/1
  # DELETE /favorite_categories/1.json
  def destroy
    @favorite_category.destroy
    respond_to do |format|
      format.html { redirect_to favorite_categories_url, notice: 'Favorite category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_by_order
    order = params.permit(:order)[:order]
    category = FavoriteCategory.where(order: order).first
    if category.present?
      render json: { exists: true, id: category.id }
    else
      render json: { exists: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_category
      @favorite_category = current_user.favorite_categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_category_params
      params.require(:favorite_category).permit(:order, :name, :description)
    end
end

app/helpers/favorite_categories_helper.rb
module FavoriteCategoriesHelper
end

app/views/favorite_categories/_form.html.erb
<%= form_with(model: favorite_category, local: true, id: 'favorite_category_form') do |form| %>
  <% if favorite_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite_category.errors.count, "error") %> prohibited this favorite_category from being saved:</h2>

      <ul>
      <% favorite_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" id="category_id" value="<%= favorite_category.id %>">

  <div class="form-group">
    <%= form.label :order %>
    <%= form.number_field :order, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary', data: { disable_with: false} %>
  </div>
<% end %>

app/views/favorite_categories/edit.html.erb
<h1>Cambiar categoría</h1>

<%= render 'form', favorite_category: @favorite_category %>

<%= link_to 'Ver', @favorite_category %> |
<%= link_to 'Volver', favorite_categories_path %>

app/views/favorite_categories/index.html.erb
<h1>Mis favoritos</h1>

<div class="card-deck">
  <% @favorite_categories.each do |favorite_category| %>

    <div class="card">
      <img src="/categ.jpg" class="card-img-top" alt="Imagen">
      <div class="card-body">
        <h5 class="card-title"><%= favorite_category.name %></h5>
        <p class="card-text"><%= favorite_category.description %></p>
        <%= link_to "Ir al listado", favorite_category_favorites_path(favorite_category), class: 'btn btn-primary' %>
        <div class="row justify-content-end">
          <% favorite_category.comments.each do |comment| %>
            <div class="col-10 mt-2 p-2 border rounded shadow-sm">
              <%= comment.message %>
              <small class="d-block text-right text-info"><%= l(comment.created_at, format: :short) %></small>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer text-right">
        <small>

        <%= link_to 'Cambiar', edit_favorite_category_path(favorite_category), class: 'card-link text-secondary' %>
        <%= link_to 'Eliminar', favorite_category, class: 'card-link text-danger', method: :delete, data: { confirm: '¿Seguro? Se eliminarán la categoría y sus elementos' } %>
        </small>
      </div>
    </div>
  <% end %>
</div>

<p class="mt-3">
  <%= link_to 'Nueva categoría', new_favorite_category_path, class: 'btn btn-secondary' %>
</p>

app/views/favorite_categories/new.html.erb
<h1>Crear categoría</h1>

<%= render 'form', favorite_category: @favorite_category %>

<%= link_to 'Volver', favorite_categories_path %>

app/views/favorite_categories/show.html.erb
<h1 class="show-category__title">
  Categoría <span class="show-category__name"><%= @favorite_category.name %></span>
</h1>
<div class="show-category__order">(orden: <%= @favorite_category.order %>)</div>

<div class="show-category__description">
  <%= @favorite_category.description %>
</div>

<%= link_to 'Cambiar', edit_favorite_category_path(@favorite_category) %> |
<%= link_to 'Volver', favorite_categories_path %>